services:

  postgres:
    image: postgres:17
    container_name: lifelink-postgres

    environment:
      POSTGRES_DB: LifelinkDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d LifelinkDB"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

    restart: unless-stopped


  backend:
    build: .
    container_name: lifelink-backend

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/LifelinkDB
      DB_USERNAME: postgres
      DB_PASSWORD: ${DB_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}

      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

    ports:
      - "8080:8080"

    restart: unless-stopped


volumes:
  postgres_data: